workflows:
  ios_unsigned:
    name: iOS unsigned build
    max_build_duration: 60
    environment:
      xcode: 16.2
    scripts:
      # --- Debug: show what Codemagic checked out
      - name: Debug — show files
        script: |
          set -euxo pipefail
          echo "PWD: $(pwd)"
          ls -la
          echo "----- SmartwatchApp dir (top) -----"
          ls -la SmartwatchApp || true
          echo "----- SmartwatchApp (recursive) -----"
          ls -R SmartwatchApp || true

      # --- Fetch XcodeGen >= 2.42.0 and generate .xcodeproj
      - name: Fetch XcodeGen 2.42.1 and generate project
        script: |
          set -euxo pipefail
          XG_VER="2.42.1"
          XG_DIR="$CM_BUILD_DIR/tools/xcodegen"
          mkdir -p "$XG_DIR"
          curl -L --fail -o "$XG_DIR/xcodegen.zip" \
            "https://github.com/yonaskolb/XcodeGen/releases/download/$XG_VER/xcodegen.zip"
          unzip -q "$XG_DIR/xcodegen.zip" -d "$XG_DIR"
          chmod +x "$XG_DIR/xcodegen"
          "$XG_DIR/xcodegen" --version

          # Generate project from your spec
          test -f SmartwatchApp/project.yml
          "$XG_DIR/xcodegen" generate --spec SmartwatchApp/project.yml

      # --- List schemes/targets Codemagic detects (great for troubleshooting)
      - name: List Xcode targets & schemes
        script: |
          set -euxo pipefail
          xcodebuild -list -project SmartwatchApp/SmartwatchApp.xcodeproj

      # --- Build archive WITHOUT code signing
      - name: Build archive WITHOUT code signing
        script: |
          set -euxo pipefail
          mkdir -p output
          xcodebuild \
            -project SmartwatchApp/SmartwatchApp.xcodeproj \
            -scheme SmartwatchApp \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO \
            archive -archivePath output/App.xcarchive

      # --- Package the .app as a zip to download
      - name: Package .app (unsigned) as zip
        script: |
          set -euxo pipefail
          APP_PATH="output/App.xcarchive/Products/Applications/SmartwatchApp.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "Expected app not found at: $APP_PATH"
            echo "Contents of archive:"
            find output -maxdepth 4 -type d -print
            exit 1
          fi
          ditto -c -k --sequesterRsrc --keepParent "$APP_PATH" SmartwatchApp-unsigned.zip

    artifacts:
      - SmartwatchApp-unsigned.zip
