workflows:
  ios_unsigned:
    name: iOS unsigned build
    max_build_duration: 60
    environment:
      xcode: 16.2

    scripts:
      - name: Debug — show files
        script: |
          set -e
          echo "PWD: $(pwd)"
          ls -la
          echo "---- SmartwatchApp dir ----"
          ls -la SmartwatchApp || true
          echo "---- SmartwatchApp recursive ----"
          ls -R SmartwatchApp || true

      - name: List Xcode targets & schemes
        script: |
          set -e
          xcodebuild -list -project SmartwatchApp/SmartwatchApp.xcodeproj

      - name: Build archive WITHOUT code signing
        script: |
          set -e
          xcodebuild \
            -project SmartwatchApp/SmartwatchApp.xcodeproj \
            -scheme SmartwatchApp \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO \
            archive -archivePath $CM_BUILD_DIR/App.xcarchive

      - name: Package .app (unsigned) as zip
        script: |
          set -e
          APP="$CM_BUILD_DIR/App.xcarchive/Products/Applications/SmartwatchApp.app"
          if [ -d "$APP" ]; then
            cd "$(dirname "$APP")"
            zip -r "$CM_ARTIFACTS/SmartwatchApp-unsigned-app.zip" "SmartwatchApp.app"
          else
            echo "App bundle not found at $APP"
            exit 1
          fi

    artifacts:
      - $CM_BUILD_DIR/App.xcarchive
      - $CM_ARTIFACTS/SmartwatchApp-unsigned-app.zip
