workflows:
  ios_unsigned:
    name: iOS unsigned build
    max_build_duration: 60
    environment:
      xcode: 16.2
    scripts:
      - name: Debug — show files
        script: |
          set -e
          echo "PWD: $(pwd)"
          ls -la
          echo "----- SmartwatchApp dir -----"
          ls -la SmartwatchApp || true
          echo "----- SmartwatchApp recursive -----"
          ls -R SmartwatchApp || true

      - name: Fetch XcodeGen binary and generate project (no brew)
        script: |
          set -euo pipefail
          XG_VER="2.42.0"
          XG_DIR="$CM_BUILD_DIR/tools/xcodegen"
          mkdir -p "$XG_DIR"
          echo "Downloading XcodeGen ${XG_VER}…"
          curl -L --fail -o "$XG_DIR/xcodegen.zip" "https://github.com/yonaskolb/XcodeGen/releases/download/${XG_VER}/xcodegen.zip"

          echo "Unzipping…"
          unzip -q "$XG_DIR/xcodegen.zip" -d "$XG_DIR"
          # the zip contains a single 'xcodegen' executable
          chmod +x "$XG_DIR/xcodegen"

          echo "XcodeGen version:"
          "$XG_DIR/xcodegen" --version

          echo "Generating Xcode project from SmartwatchApp/project.yml…"
          "$XG_DIR/xcodegen" generate --spec SmartwatchApp/project.yml

      - name: List Xcode targets & schemes
        script: |
          set -e
          xcodebuild -list -project SmartwatchApp/SmartwatchApp.xcodeproj

      - name: Build archive WITHOUT code signing
        script: |
          set -e
          mkdir -p output
          xcodebuild \
            -project SmartwatchApp/SmartwatchApp.xcodeproj \
            -scheme SmartwatchApp \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO \
            -archivePath output/App.xcarchive \
            clean archive

      - name: Package .app (unsigned) as zip
        script: |
          set -e
          APP_PATH="output/App.xcarchive/Products/Applications/SmartwatchApp.app"
          if [ -d "$APP_PATH" ]; then
            ditto -ck --sequesterRsrc --keepParent "$APP_PATH" output/SmartwatchApp-unsigned.zip
          else
            echo "App not found at $APP_PATH"
            exit 1
          fi

    artifacts:
      - output/SmartwatchApp-unsigned.zip
