workflows:
  ios_unsigned:
    name: iOS unsigned build
    max_build_duration: 60
    environment:
      xcode: 16.2

    scripts:
      - name: Debug — show files
        script: |
          set -e
          echo "PWD: $(pwd)"
          ls -la
          echo "---- SmartwatchApp dir (top) ----"
          ls -la SmartwatchApp || true
          echo "---- SmartwatchApp recursive ----"
          ls -R SmartwatchApp || true

      - name: Fetch XcodeGen binary and generate project (no brew)
        script: |
          set -euo pipefail
          XG_VER="2.41.0"
          XG_DIR="$CM_BUILD_DIR/tools"
          mkdir -p "$XG_DIR"
          echo "Downloading XcodeGen ${XG_VER}…"
          curl -L -o "$XG_DIR/xcodegen.zip" "https://github.com/yonaskolb/XcodeGen/releases/download/${XG_VER}/xcodegen.zip"
          unzip -q "$XG_DIR/xcodegen.zip" -d "$XG_DIR"
          XG_BIN="$XG_DIR/xcodegen"
          chmod +x "$XG_BIN"
          echo "XcodeGen at: $XG_BIN"
          "$XG_BIN" --version
          echo "Generating Xcode project from SmartwatchApp/project.yml…"
          (cd SmartwatchApp && "$XG_BIN" generate)
          echo "Result:"
          ls -la SmartwatchApp/SmartwatchApp.xcodeproj

      - name: List Xcode targets & schemes
        script: |
          set -e
          xcodebuild -list -project SmartwatchApp/SmartwatchApp.xcodeproj

      - name: Build archive WITHOUT code signing
        script: |
          set -e
          xcodebuild \
            -project SmartwatchApp/SmartwatchApp.xcodeproj \
            -scheme SmartwatchApp \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO \
            archive -archivePath $CM_BUILD_DIR/App.xcarchive

      - name: Package .app (unsigned) as zip
        script: |
          set -e
          APP="$CM_BUILD_DIR/App.xcarchive/Products/Applications/SmartwatchApp.app"
          if [ -d "$APP" ]; then
            cd "$(dirname "$APP")"
            zip -r "$CM_ARTIFACTS/SmartwatchApp-unsigned-app.zip" "SmartwatchApp.app"
          else
            echo "App bundle not found at $APP"
            exit 1
          fi

    artifacts:
      - $CM_BUILD_DIR/App.xcarchive
      - $CM_ARTIFACTS/SmartwatchApp-unsigned-app.zip
