name: SmartwatchApp

# Global (base) build settings
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    SWIFT_VERSION: "5.9"

# The iOS app target
targets:
  SmartwatchApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      # This includes all app sources already in SmartwatchApp/
      - path: SmartwatchApp
    info:
      path: SmartwatchApp/Info.plist

# Create a shared scheme named "SmartwatchApp"
schemes:
  SmartwatchApp:
    shared: true
    build:
      targets:
        SmartwatchApp: all
    run:
      config: Release
    archive:
      config: Release
