name: SmartwatchApp

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    SWIFT_VERSION: "5.9"

targets:
  SmartwatchApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    bundleId: com.546prints.smartwatchapp      # <— ADD/KEEP THIS
    sources:
      - path: SmartwatchApp
    info:
      path: SmartwatchApp/Info.plist
