name: SmartwatchApp
options:
  minimumXcodeGenVersion: 2.42.0

targets:
  SmartwatchApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
    resources:
      - path: Resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.546prints.smartwatchapp
      INFOPLIST_FILE: Resources/Info.plist
