name: SmartwatchApp
options:
  minimumXcodeGenVersion: 2.37.0
  deploymentTarget:
    iOS: "15.0"

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.546prints.smartwatchapp
    INFOPLIST_FILE: SmartwatchApp/Resources/Info.plist
    SWIFT_VERSION: 5.9
    TARGETED_DEVICE_FAMILY: "1"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"

targets:
  SmartwatchApp:
    type: application
    platform: iOS
    sources:
      - path: SmartwatchApp/Sources
    resources:
      - path: SmartwatchApp/Resources
    settings:
      base:
        PRODUCT_NAME: SmartwatchApp
        INFOPLIST_FILE: SmartwatchApp/Resources/Info.plist
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: ""
        PROVISIONING_PROFILE_SPECIFIER: ""
    scheme:
      name: SmartwatchApp
      testTargets: []
