name: SmartwatchApp
options:
  minimumXcodeGenVersion: 2.42.0

targets:
  SmartwatchApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
    resources:
      - path: Resources
    settings:
      # App identity
      PRODUCT_BUNDLE_IDENTIFIER: com.546prints.smartwatchapp
      INFOPLIST_FILE: Resources/Info.plist

      # ---- Force NO code signing / manual signing ----
      CODE_SIGN_STYLE: Manual
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGN_IDENTITY: ""
      DEVELOPMENT_TEAM: ""
      PROVISIONING_PROFILE_SPECIFIER: ""
