name: Build iOS App (unsigned)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode (prefer 16.2, fallback 15.4)
        shell: bash
        run: |
          if [ -d "/Applications/Xcode_16.2.app" ]; then
            sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
          elif [ -d "/Applications/Xcode_15.4.app" ]; then
            sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
          fi
          xcodebuild -version

      - name: Debug – list files
        run: |
          pwd
          ls -la
          echo "----- tree -----"
          ls -R SmartwatchApp || true

      # Optional: only runs if you add SmartwatchApp/project.yml later
      - name: Install XcodeGen (optional)
        run: |
          brew update
          brew install xcodegen
      - name: Generate Xcode project from project.yml (optional)
        working-directory: SmartwatchApp
        run: |
          if [ -f project.yml ]; then
            xcodegen generate --spec project.yml
          else
            echo "No project.yml found; using existing .xcodeproj"
          fi

      - name: Build (archive) WITHOUT code signing
        shell: bash
        run: |
          mkdir -p output
          xcodebuild \
            -project SmartwatchApp/SmartwatchApp.xcodeproj \
            -scheme SmartwatchApp \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGN_STYLE=Automatic \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            -archivePath output/App.xcarchive \
            clean archive

      - name: Create unsigned IPA
        shell: bash
        run: |
          APP_PATH="output/App.xcarchive/Products/Applications/SmartwatchApp.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "App bundle not found at: $APP_PATH"
            exit 1
          fi
          rm -rf Payload
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          /usr/bin/zip -qry SmartwatchApp-unsigned.ipa Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmartwatchApp-unsigned
          path: SmartwatchApp-unsigned.ipa
