      - name: Build (archive) WITHOUT code signing
        run: |
          mkdir -p output
          xcodebuild \
            -project SmartwatchApp/SmartwatchApp.xcodeproj \
            -scheme SmartwatchApp \
            -configuration Release \
            -sdk iphoneos \
            -archivePath output/App.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            clean archive

      - name: Create unsigned IPA manually
        run: |
          APP_PATH="output/App.xcarchive/Products/Applications/SmartwatchApp.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "App not found at $APP_PATH"; exit 1
          fi
          rm -rf Payload && mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          cd Payload
          zip -r ../SmartwatchApp-unsigned.ipa . -q
          cd ..
          ls -la output || true
          mv SmartwatchApp-unsigned.ipa output/

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: smartwatch-app-unsigned
          path: output/SmartwatchApp-unsigned.ipa
