name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install fastlane
        run: gem install fastlane

      - name: Install CocoaPods dependencies
        run: |
          gem install cocoapods
          pod install || true
        working-directory: .

      - name: Build IPA with Fastlane
        run: fastlane build

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: MyApp.ipa
          path: ./build/*.ipa
