name: Build iOS App (unsigned IPA)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode (prefer 16.2, fallback 15.4)
        run: sudo xcode-select -s "/Applications/Xcode_16.2.app" || sudo xcode-select -s "/Applications/Xcode_15.4.app"

      - name: Debug – list files
        run: ls -R

      - name: Debug – show bundle id values
        run: |
          echo "Using PRODUCT_BUNDLE_IDENTIFIER = com.546prints.smartwatchapp"
          echo "INFOPLIST_FILE = SmartwatchApp/Info.plist"

      - name: Build (archive) WITHOUT code signing
        run: |
          set -e
          xcodebuild \
            -project SmartwatchApp/SmartwatchApp.xcodeproj \
            -scheme SmartwatchApp \
            -configuration Release \
            -sdk iphoneos \
            PRODUCT_BUNDLE_IDENTIFIER=com.546prints.smartwatchapp \
            INFOPLIST_FILE=SmartwatchApp/Info.plist \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO \
            -archivePath output/App.xcarchive \
            clean archive

      - name: Create unsigned IPA
        run: |
          mkdir -p output
          xcodebuild -exportArchive -archivePath output/App.xcarchive -exportPath output -exportOptionsPlist ExportOptions.plist

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmartwatchApp
          path: output/*.ipa
