name: Build iOS App (unsigned)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode (prefer 16.2, fallback 15.4)
        shell: bash
        run: |
          if [ -d "/Applications/Xcode_16.2.app" ]; then
            sudo xcode-select -s /Applications/Xcode_16.2.app
          else
            sudo xcode-select -s /Applications/Xcode_15.4.app
          fi
          xcodebuild -version

      - name: Debug — list files
        run: |
          pwd
          ls -la
          echo "----- SmartwatchApp dir -----"
          ls -la SmartwatchApp

      - name: Install XcodeGen
        run: |
          brew update
          brew install xcodegen

      - name: Debug — show project.yml
        run: |
          cat SmartwatchApp/project.yml || true

      - name: Generate Xcode project from project.yml
        run: |
          test -f SmartwatchApp/project.yml
          xcodegen generate --spec SmartwatchApp/project.yml

      - name: Build (archive) WITHOUT code signing
        run: |
          set -e
          mkdir -p output
          xcodebuild \
            -project SmartwatchApp/SmartwatchApp.xcodeproj \
            -scheme SmartwatchApp \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            PRODUCT_BUNDLE_IDENTIFIER=com.546prints.smartwatchapp \
            INFOPLIST_FILE=Resources/Info.plist \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            -archivePath output/App.xcarchive \
            clean archive

      - name: Create unsigned IPA
        run: |
          set -e
          APP_PATH="output/App.xcarchive/Products/Applications/SmartwatchApp.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "App not found at $APP_PATH"
            exit 1
          fi
          mkdir -p output/Payload
          cp -R "$APP_PATH" output/Payload/
          (cd output && zip -r SmartwatchApp-unsigned.ipa Payload)

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmartwatchApp-unsigned
          path: output/SmartwatchApp-unsigned.ipa
