name: Build iOS App (unsigned)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Prefer Xcode 16.2; fall back to 15.4 if needed
      - name: Select Xcode (prefer 16.2, fallback 15.4)
        run: |
          if [ -d "/Applications/Xcode_16.2.app" ]; then
            sudo xcode-select -s /Applications/Xcode_16.2.app
          elif [ -d "/Applications/Xcode_15.4.app" ]; then
            sudo xcode-select -s /Applications/Xcode_15.4.app
          fi
          xcodebuild -version

      - name: Debug – list files
        run: |
          pwd
          ls -la
          echo "----- SmartwatchApp dir -----"
          ls -la SmartwatchApp || true

      - name: Show bundle id values
        run: |
          echo "Bundle id expected: com.546prints.smartwatchapp"
          echo "Info.plist path   : SmartwatchApp/Resources/Info.plist"

      # --- Generate the Xcode project ---
      - name: Install XcodeGen
        run: |
          brew update
          brew install xcodegen

      - name: Debug — show project.yml
        run: |
          echo "----- project.yml -----"
          sed -n '1,200p' SmartwatchApp/project.yml

      - name: Generate Xcode project from project.yml
        run: |
          test -f SmartwatchApp/project.yml
          xcodegen generate --spec SmartwatchApp/project.yml
          echo "----- generated root -----"
          ls -la
          echo "----- SmartwatchApp dir after generate -----"
          ls -la SmartwatchApp

      # --- Build WITHOUT code signing (for archive only) ---
      - name: Build (archive) WITHOUT code signing
        run: |
          mkdir -p output
          xcodebuild \
            -project SmartwatchApp/SmartwatchApp.xcodeproj \
            -scheme SmartwatchApp \
            -configuration Release \
            -sdk iphones \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            -archivePath output/App.xcarchive \
            clean archive

      - name: Create unsigned IPA
        run: |
          APP_PATH="output/App.xcarchive/Products/Applications/SmartwatchApp.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "App not found at $APP_PATH"
            exit 1
          fi
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          zip -y -r SmartwatchApp-unsigned.ipa Payload
          rm -rf Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmartwatchApp-unsigned
          path: SmartwatchApp-unsigned.ipa
